prefix : <http:/test.com/>

select distinct ?o1 ?o2

where {
  GRAPH ?g1 { ?s :knows ?o1.  } VALUES ?g1 {<test>}
  MINUS { GRAPH ?g_minus { ?s :knows ?o1. } VALUES ?g_minus {} }
  
  GRAPH ?g2 { ?s :knows ?o2.  } VALUES ?g2 {<test>}
  MINUS { GRAPH ?g_minus { ?s :knows ?o2. } VALUES ?g_minus {} }
  
  FILTER (?o1 != ?o2)
  
}