prefix rmo:	<http://eatld.et.tu-dresden.de/rmo#>
prefix prov:	<http://www.w3.org/ns/prov#> 

select distinct ?s ?p ?o

where {
	GRAPH ?g1 { ?s ?p ?o. }
  		{ <r43ples-test-dataset-master> rmo:fullGraph ?g1. } UNION
  		{ ?rg1 a rmo:Revision.
  		  ?rg1 rmo:deltaRemoved ?g1.
          FILTER (?rg1 IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
        }
  	MINUS {
		GRAPH ?gm1 { ?s ?p ?o. }
  			?rm1 a rmo:Revision.
  			?rm1 rmo:deltaAdded ?gm1.
  			FILTER (?rm1 IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
  			MINUS {
  				GRAPH ?gm1_old {?s ?p ?o.}
  				?rm1_old a rmo:Revision.
  				?rm1_old rmo:deltaRemoved ?gm1_old.
  				?rm1_old prov:wasDerivedFrom+ ?rm1.
  				FILTER (?rm1_old IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
			}
  	} 
}