prefix : <http:/test.com/>
prefix rmo:	<http://eatld.et.tu-dresden.de/rmo#>
prefix prov:	<http://www.w3.org/ns/prov#> 

select distinct ?s ?p ?o

where {
	GRAPH ?g1 { ?s ?p ?o. }
  		{ <r43ples-test-dataset-master> rmo:fullGraph ?g1. } UNION
  		{ ?rg1 a rmo:Revision; rmo:deltaRemoved ?g1. VALUES ?rg1 {<r43ples-test-dataset-revision-4> <r43ples-test-dataset-revision-3>} }
  	MINUS {
		GRAPH ?gm1 { ?s ?p ?o. }
  			?rm1 a rmo:Revision; rmo:deltaAdded ?gm1.
  			VALUES ?rm1 {<r43ples-test-dataset-revision-4> <r43ples-test-dataset-revision-3>}
  			MINUS {
  			    # Following line is not working with Virtuoso 7. Don't know why
  				# ?rm1_old a rmo:Revision.
  				#?rm1 a rmo:Revision; prov:wasDerivedFrom+ ?rm1_old.
  		        # following lines are a work-around
  				?rm1 rmo:revisionNumber ?rm1_n.
  				?rm1_old rmo:revisionNumber ?rm1_old_n.
  				FILTER (?rm1_old_n < ?rm1_n)
  				
  				VALUES ?rm1_old {<r43ples-test-dataset-revision-4> <r43ples-test-dataset-revision-3>}
  				?rm1_old rmo:deltaRemoved ?gm1_old.
  				GRAPH ?gm1_old {?s ?p ?o. }
			}
  	} 
  	
 
}