prefix rmo:	<http://eatld.et.tu-dresden.de/rmo#>
prefix prov:	<http://www.w3.org/ns/prov#> 

prefix : <http:/test.com/>

select distinct ?o1 ?o2
where {
	GRAPH ?g1 { ?s :knows ?o1. }
  		{ <r43ples-test-dataset-master> rmo:fullGraph ?g1. } UNION
  		{ ?rg1 a rmo:Revision.
  		  ?rg1 rmo:deltaRemoved ?g1.
  		  FILTER (?rg1 IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
  		}
  	MINUS {
		GRAPH ?gm1 { ?s :knows ?o1. }
  			?rm1 a rmo:Revision.
  			?rm1 rmo:deltaAdded ?gm1.
  			FILTER (?rm1 IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
  			MINUS {
  				GRAPH ?gm1_old {?s :knows ?o1.}
  				?rm1_old a rmo:Revision.
  				?rm1_old rmo:deltaRemoved ?gm1_old.
  				?rm1_old prov:wasDerivedFrom+ ?rm1.
  				FILTER (?rm1_old IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
			}
  	} 
  	
  	
  	GRAPH ?g2 { ?s :knows ?o2. }
  		{ <r43ples-test-dataset-master> rmo:fullGraph ?g2. } UNION
  		{ ?rg2 a rmo:Revision.
  		  ?rg2 rmo:deltaRemoved ?g2.
  		  FILTER (?rg2 IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
  		}
  	MINUS {
		GRAPH ?gm2 { ?s :knows ?o2. }
  			?rm2 a rmo:Revision.
  			?rm2 rmo:deltaAdded ?gm2.
  			FILTER (?rm2 IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
  			MINUS {
  				GRAPH ?gm2_old {?s :knows ?o2. }
  				?rm2_old a rmo:Revision.
  				?rm2_old rmo:deltaRemoved ?gm2_old.
  				?rm2_old prov:wasDerivedFrom+ ?rm2.
  				FILTER (?rm2_old IN (<r43ples-test-dataset-revision-4>, <r43ples-test-dataset-revision-3>, <r43ples-test-dataset-revision-2>))
			}
  	} 
  	
  	FILTER (?o1 != ?o2)
}