PREFIX  :     <http://test.com/>

SELECT DISTINCT  ?p1 ?p2
WHERE
  { { { GRAPH ?g_delete_set_full_graph_1
          { ?p1  :knows  ?p2 .}
        GRAPH <http://eatld.et.tu-dresden.de/r43ples-revisions>
          { { ?reference_1  <http://eatld.et.tu-dresden.de/rmo#references>  ?r_fullgraph1 ;
                        <http://eatld.et.tu-dresden.de/rmo#fullGraph>  ?g_delete_set_full_graph_1 .
              FILTER ( ?r_fullgraph1 IN (<http://test_dataset_user-revision-5>) )
            }
            UNION
              { ?r_delete_set_1
                          <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                          <http://eatld.et.tu-dresden.de/rmo#deltaRemoved>  ?g_delete_set_full_graph_1 .
                FILTER ( ?r_delete_set_1 IN (<http://test_dataset_user-revision-5>, <http://test_dataset_user-revision-4>, <http://test_dataset_user-revision-3>) )
              }
          }
        MINUS
          { GRAPH ?g_add_set_1
              { ?p1  :knows  ?p2 .}
            GRAPH <http://eatld.et.tu-dresden.de/r43ples-revisions>
              { ?r_add_set_1  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                          <http://eatld.et.tu-dresden.de/rmo#deltaAdded>  ?g_add_set_1 .
                FILTER ( ?r_add_set_1 IN (<http://test_dataset_user-revision-5>, <http://test_dataset_user-revision-4>, <http://test_dataset_user-revision-3>) )
              }
            MINUS
              { GRAPH ?g_delta_set_old_1
                  { ?p1  :knows  ?p2 .}
                GRAPH <http://eatld.et.tu-dresden.de/r43ples-revisions>
                  { ?r_delta_set_old_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://eatld.et.tu-dresden.de/rmo#Revision> .
                    ?r_delta_set_old_1 <http://eatld.et.tu-dresden.de/rmo#deltaRemoved>|<http://eatld.et.tu-dresden.de/rmo#deltaAdded> ?g_delta_set_old_1 .
                    ?r_add_set_1 (<http://www.w3.org/ns/prov#wasDerivedFrom>)+ ?r_delta_set_old_1
                    FILTER ( ?r_delta_set_old_1 IN (<http://test_dataset_user-revision-5>, <http://test_dataset_user-revision-4>, <http://test_dataset_user-revision-3>) )
                  }
              }
          }
      }
      MINUS
        { { GRAPH ?g_delete_set_full_graph_2
              { ?p1  :knows  :Danny .}
            GRAPH <http://eatld.et.tu-dresden.de/r43ples-revisions>
              { { ?reference_2  <http://eatld.et.tu-dresden.de/rmo#references>  ?r_fullgraph2 ;
                            <http://eatld.et.tu-dresden.de/rmo#fullGraph>  ?g_delete_set_full_graph_2 .
                  FILTER ( ?r_fullgraph2 IN (<http://test_dataset_user-revision-5>) )
                }
                UNION
                  { ?r_delete_set_2
                              <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                              <http://eatld.et.tu-dresden.de/rmo#deltaRemoved>  ?g_delete_set_full_graph_2 .
                    FILTER ( ?r_delete_set_2 IN (<http://test_dataset_user-revision-5>, <http://test_dataset_user-revision-4>, <http://test_dataset_user-revision-3>) )
                  }
              }
            MINUS
              { GRAPH ?g_add_set_2
                  { ?p1  :knows  :Danny .}
                GRAPH <http://eatld.et.tu-dresden.de/r43ples-revisions>
                  { ?r_add_set_2  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                              <http://eatld.et.tu-dresden.de/rmo#deltaAdded>  ?g_add_set_2 .
                    FILTER ( ?r_add_set_2 IN (<http://test_dataset_user-revision-5>, <http://test_dataset_user-revision-4>, <http://test_dataset_user-revision-3>) )
                  }
                MINUS
                  { GRAPH ?g_delta_set_old_2
                      { ?p1  :knows  :Danny .}
                    GRAPH <http://eatld.et.tu-dresden.de/r43ples-revisions>
                      { ?r_delta_set_old_2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://eatld.et.tu-dresden.de/rmo#Revision> .
                        ?r_delta_set_old_2 <http://eatld.et.tu-dresden.de/rmo#deltaRemoved>|<http://eatld.et.tu-dresden.de/rmo#deltaAdded> ?g_delta_set_old_2 .
                        ?r_add_set_2 (<http://www.w3.org/ns/prov#wasDerivedFrom>)+ ?r_delta_set_old_2
                        FILTER ( ?r_delta_set_old_2 IN (<http://test_dataset_user-revision-5>, <http://test_dataset_user-revision-4>, <http://test_dataset_user-revision-3>) )
                      }
                  }
              }
          }
        }
    }
  }
ORDER BY ?p1 ?p2
