PREFIX  :     <http://test.com/>

SELECT DISTINCT  ?p1 ?p2
WHERE
  { GRAPH ?g_delete_set_full_graph_1
      { ?p1  :knows  ?p2 .}
    GRAPH :r43ples-dataset-1-revisiongraph
      {   { _:b0  <http://eatld.et.tu-dresden.de/rmo#references>  ?r_delete_set_1 ;
                  <http://eatld.et.tu-dresden.de/rmo#fullGraph>  ?g_delete_set_full_graph_1 .
            FILTER ( ?r_delete_set_1 = :r43ples-dataset-1-revision-6 )
          }
        UNION
          { ?r_delete_set_1
                      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                      <http://eatld.et.tu-dresden.de/rmo#deleteSet>  ?g_delete_set_full_graph_1 .
            FILTER ( ?r_delete_set_1 IN (:r43ples-dataset-1-revision-6, :r43ples-dataset-1-revision-5, :r43ples-dataset-1-revision-4) )
          }
      }
    MINUS
      { GRAPH ?g_add_set_1
          { ?p1  :knows  ?p2 .}
        GRAPH :r43ples-dataset-1-revisiongraph
          { ?r_delete_set_1 (<http://www.w3.org/ns/prov#wasDerivedFrom>)* ?r_add_set_1 . 
            ?r_add_set_1  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                      <http://eatld.et.tu-dresden.de/rmo#addSet>  ?g_add_set_1 .
            FILTER ( ?r_add_set_1 IN (:r43ples-dataset-1-revision-6, :r43ples-dataset-1-revision-5, :r43ples-dataset-1-revision-4) )
          }
      }
    MINUS
      { GRAPH ?g_delete_set_full_graph_2
          { ?p1  :knows  :Danny .}
        GRAPH :r43ples-dataset-1-revisiongraph
          {   { _:b1  <http://eatld.et.tu-dresden.de/rmo#references>  ?r_delete_set_2 ;
                      <http://eatld.et.tu-dresden.de/rmo#fullGraph>  ?g_delete_set_full_graph_2 .
                FILTER ( ?r_delete_set_2 = :r43ples-dataset-1-revision-6 )
              }
            UNION
              { ?r_delete_set_2
                          <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                          <http://eatld.et.tu-dresden.de/rmo#deleteSet>  ?g_delete_set_full_graph_2 .
                FILTER ( ?r_delete_set_2 IN (:r43ples-dataset-1-revision-6, :r43ples-dataset-1-revision-5, :r43ples-dataset-1-revision-4) )
              }
          }
        MINUS
          { GRAPH ?g_add_set_2
              { ?p1  :knows  :Danny .}
            GRAPH :r43ples-dataset-1-revisiongraph
              { ?r_delete_set_2 (<http://www.w3.org/ns/prov#wasDerivedFrom>)* ?r_add_set_2 . 
                ?r_add_set_2  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://eatld.et.tu-dresden.de/rmo#Revision> ;
                          <http://eatld.et.tu-dresden.de/rmo#addSet>  ?g_add_set_2 .
                FILTER ( ?r_add_set_2 IN (:r43ples-dataset-1-revision-6, :r43ples-dataset-1-revision-5, :r43ples-dataset-1-revision-4) )
              }
          }
      }
  }
ORDER BY ?p1 ?p2
